/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:07 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, NSString, NSURL, UIImage, UIColor;

@interface UIPasteboard : NSObject

@property (nonatomic,copy,readonly) NSArray * availableTypes; 
@property (nonatomic,readonly) long long _changeCountIgnoringPinningActivity; 
@property (nonatomic,readonly) NSString * name; 
@property (getter=isPersistent,nonatomic,readonly) BOOL persistent; 
@property (nonatomic,readonly) long long changeCount; 
@property (nonatomic,copy) NSArray * itemProviders; 
@property (nonatomic,readonly) NSArray * pasteboardTypes; 
@property (nonatomic,readonly) long long numberOfItems; 
@property (nonatomic,copy) NSArray * items; 
@property (nonatomic,copy) NSString * string; 
@property (nonatomic,copy) NSArray * strings; 
@property (nonatomic,copy) NSURL * URL; 
@property (nonatomic,copy) NSArray * URLs; 
@property (nonatomic,copy) UIImage * image; 
@property (nonatomic,copy) NSArray * images; 
@property (nonatomic,copy) UIColor * color; 
@property (nonatomic,copy) NSArray * colors; 
@property (nonatomic,readonly) BOOL hasStrings; 
@property (nonatomic,readonly) BOOL hasURLs; 
@property (nonatomic,readonly) BOOL hasImages; 
@property (nonatomic,readonly) BOOL hasColors; 
+(void)_pinItemProviders:(id)arg1 forPasteboardNamed:(id)arg2 withExpirationDate:(id)arg3 ;
+(id)generalPasteboard;
+(id)_pasteboardWithUniqueName;
+(id)pasteboardWithUniqueName;
+(id)pasteboardWithName:(id)arg1 create:(BOOL)arg2 ;
+(id)_pasteboardWithName:(id)arg1 create:(BOOL)arg2 ;
+(void)removePasteboardWithName:(id)arg1 ;
+(void)_clearPinnedItemProvidersForPasteboardNamed:(id)arg1 ;
-(long long)changeCount;
-(void)setItems:(NSArray *)arg1 ;
-(void)setObjects:(id)arg1 ;
-(UIImage *)image;
-(BOOL)isPersistent;
-(BOOL)hasURLs;
-(void)setColors:(NSArray *)arg1 ;
-(BOOL)hasStrings;
-(void)setName:(NSString *)arg1 ;
-(void)_clearPinnedItemProviders;
-(void)_pinItemProviders:(id)arg1 expirationDate:(id)arg2 ;
-(void)setImages:(NSArray *)arg1 ;
-(void)addItems:(id)arg1 ;
-(NSArray *)URLs;
-(BOOL)hasImages;
-(BOOL)hasColors;
-(NSString *)name;
-(BOOL)_hasStrings;
-(NSArray *)items;
-(NSArray *)availableTypes;
-(NSString *)string;
-(NSArray *)pasteboardTypes;
-(void)setImage:(UIImage *)arg1 ;
-(id)dataForPasteboardType:(id)arg1 ;
-(id)valueForPasteboardType:(id)arg1 ;
-(BOOL)containsPasteboardTypes:(id)arg1 ;
-(long long)_changeCountIgnoringPinningActivity;
-(void)setValue:(id)arg1 forPasteboardType:(id)arg2 ;
-(NSArray *)colors;
-(void)setData:(id)arg1 forPasteboardType:(id)arg2 ;
-(id)pasteboardTypesForItemSet:(id)arg1 ;
-(BOOL)containsPasteboardTypes:(id)arg1 inItemSet:(id)arg2 ;
-(id)itemSetWithPasteboardTypes:(id)arg1 ;
-(id)valuesForPasteboardType:(id)arg1 inItemSet:(id)arg2 ;
-(void)setItems:(id)arg1 options:(id)arg2 ;
-(id)dataForPasteboardType:(id)arg1 inItemSet:(id)arg2 ;
-(void)setItemProviders:(id)arg1 options:(id)arg2 ;
-(void)setItemProviders:(id)arg1 localOnly:(BOOL)arg2 expirationDate:(id)arg3 ;
-(void)setObjects:(id)arg1 options:(id)arg2 ;
-(void)setObjects:(id)arg1 localOnly:(BOOL)arg2 expirationDate:(id)arg3 ;
-(BOOL)canInstantiateObjectsOfClass:(Class)arg1 ;
-(id)itemProvidersForInstantiatingObjectsOfClass:(Class)arg1 ;
-(id)_detectedPasteboardTypesForTypes:(id)arg1 ;
-(id)_detectedPasteboardTypeStringsForTypes:(id)arg1 ;
-(void)detectPatternsForPatterns:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)detectPatternsForPatterns:(id)arg1 inItemSet:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)detectValuesForPatterns:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(void)detectValuesForPatterns:(id)arg1 inItemSet:(id)arg2 completionHandler:(/*^block*/id)arg3 ;
-(void)setURLs:(NSArray *)arg1 ;
-(void)setStrings:(NSArray *)arg1 ;
-(NSArray *)itemProviders;
-(NSURL *)URL;
-(void)setItemProviders:(NSArray *)arg1 ;
-(UIColor *)color;
-(NSArray *)strings;
-(void)setString:(NSString *)arg1 ;
-(NSArray *)images;
-(void)setURL:(NSURL *)arg1 ;
-(void)setPersistent:(BOOL)arg1 ;
-(void)setColor:(UIColor *)arg1 ;
-(long long)numberOfItems;
@end
